### ISSUE TITLE
Cubes endpoint is not available in the online instance

### ISSUE THREAD

**Issue by larjohn** [openspending/openspending#1071]
I tried accessing http://next.openspending.org/api/3/cubes/
It gives me a 404.

**Comment by akariv** [comment]
Since we introduced the concept of 'private' datasets in OpenSpending, we removed access to the `cubes` endpoint in favour of the `search/package` one:
http://next.openspending.org/search/package

Other babbage APIs are still functional, e.g.
http://next.openspending.org/api/3/cubes/525a389a219b4aa66f2b2b94311c76e5:flanders_2014_revenues_expenditures/model
