### ISSUE TITLE
more geographical levels needed

### ISSUE THREAD

**Issue by afroleadership** [openspending/openspending#1085]
We have tried to upload a dataset from a council in Cameroon and found that we need to add some geographical levels. Cameroon (Country) has regions (10 in total). Each region has divisions (58 in total). Each division has districts (360 in total). So if one wants to agregate data in a single region or in a single division, we will need to specify region/division/district when uploading data.
Example.
Continent - Africa
Country - Cameroon
Region - Center
Division - Mfoundi
District - Yaounde
City - Yaounde

**Comment by VictoriaVlad** [comment]
Hi, @afroleadership, thank you for reporting this. In my understanding, your immediate need is to have districts (not only cities) added at step 3 of OS Packager. Does your data reflect otherwise (what geo levels do you have in your data)?

![metadata](https://cloud.githubusercontent.com/assets/17012538/18257103/64c76428-7373-11e6-9ad2-157dd5118adc.jpg)

**Comment by afroleadership** [comment]
Thanks Victoria
In budget reports - datasets, we dont actually have geo data. But we normally have these levels : Council, City, Sub-division, Division, Region and Country. 

So I was thinking about aggregating datasets that belong to a same city (some cities have many of what they call urban councils), to a same sub-division, to a same division, to a same region... and then all dataset in Cameroon. It would be interesting if we have it like in the attached image.
![os cameroon geo position](https://cloud.githubusercontent.com/assets/21296716/18265334/25549fc8-740d-11e6-805e-025a9c8843d9.jpg)

Charlie Martial Ngounou
AfroLeadership, Cameroon.
