### ISSUE TITLE
OS-client: documentation

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1102]
Most of documentation for gobble has actually already been written, but the client API has changed a bit since. 
- [x] Update the README to reflect changes in the API
- [ ] Update the tutorial to reflect changes in the API
- [ ] Export the [tutorial](https://github.com/openspending/gobble/blob/master/tutorial.ipynb) as `.rst` and add it [OS-docs](https://github.com/openspending/docs)
- [ ] Add a short _asciinema_ to the README to showcase the CLI
- [ ] Deal with the Markdown rendering problem on PyPi 

@vitorbaptista you showed a trick to convert `.md` to `.rst`on the fly for PyPi but I didn't have time to note it down. Could you point me in the right direction please?

**Comment by vitorbaptista** [comment]
@cyberbikepunk For converting you can use `pandoc`. You can try online as http://pandoc.org/try/. I never used it to convert on the fly, as it always felt like too much work just to use a different syntax. My suggestion on the talk was to simply use `rst`. That pandoc link helps if you want to migrate to `rst`, as you can convert whatever you have at the moment and then just use/change the `rst` directly.

You can find the slides on http://vitorbaptista.com/pyconuk2016-developing-python-packages/

**Comment by pwalsh** [comment]
https://coderwall.com/p/qawuyq/use-markdown-readme-s-in-python-modules

**Comment by cyberbikepunk** [comment]
@vitorbaptista and @pwalsh thanks for the great tips.

**Comment by vitorbaptista** [comment]
The link @pwalsh suggested has the drawback of making the project require `pandoc` to install. Pandoc is a big package that requires compiling, so it'll end up slowing the install process.

In that post's comments, `xiongchiamiov` suggestes a code that uses `pandoc` if it's installed, otherwise it'll just add an empty description. This seems like an OK compromise.

These issues are the reason I rather not convert on the fly.

**Comment by pwalsh** [comment]
The check if pandoc is installed is fine: it will mean that the author, pushing to pypi, should have pandoc installed, and it will not matter much for anyone else.

@cyberbikepunk just to be clear, this is something a couple of us talked about before, and while I get the issues with pypi, I'm still insisting we use markdown. I like rst, I used it exclusively for many years, but I'd rather standardise on markdown across all our projects, and optimise for contribution on github, rather than display of info on the pypi website.

Also, in relation to your point about exporting the tutorial as rst for os-docs - also not necessary: os-docs is in markdown, because readthedocs supports markdown via the great [mkdocs](https://github.com/openspending/docs/blob/master/requirements.txt#L1) package - check the code there for confirmation.

**Comment by pwalsh** [comment]
Moved to https://github.com/openspending/openspending/issues/1326
