### ISSUE TITLE
Show only available filter values

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1114]
Right now we use the 'members' api call to get possible values for each filter when the application loads.

This issue changes this behaviour. Now, any change in selected filters will also reload the list of possible values with the newly applied filters.

This means we will need to:
- Lazy load the filters (and have some loading indicator there)
- Things that depend on the filter values need to be adapted as well (e.g. is pivot table available or not)
- Whenever the state changes wrt filtering, reload the filters.

**Comment by kravets-levko** [comment]
`tl;dr` To implement this feature, we need new API that will return dimension values depending on selected filters. It may be extended `/members` endpoint with `cut` parameter (like in `aggregate`).

-------------------------------------------

Let's look at an example dataset:
```
 A  | B  | C
----+----+----
 a1 | b1 | c1
----+----+----
 a1 | b2 | c1
----+----+----
 a2 | b1 | c1
----+----+----
 a2 | b2 | c1
----+----+----
 a3 | b1 | c1
```
Initially we'll have three filters for it: `A {a1, a2, a3}`, `B {b1, b2}` and `C {c1, c2}`. Assume that user is working with filter `A` and he/she selected `a1` value. If we'll just reload all filters using selected `(a1)` cut - we'll have very bad situation: `A {a1}` (because there are only rows with `a1` value in column `A`!) and `B (b1, b2)`, `C {c1}` - it is ok. Idea (and solution) for this is to not change set for `A` while user is working with it, so we'll have `A {a1, a2, a3}`, `B {b1, b2}`, `C {c1}` - and it's good: as user, if I'm filtering by one column, I can add as much values to filter as I wish because it will not reduce set of results, but add more rows to it, so it will not break any logic.

More complicated case: what if user selects more that one filter? Let's continue with example. We have selection with `(a1)` value, and filters with values (based on our great idea):  `A {a1, a2, a3}`, `B {b1, b2}` and `C {c1}`. Assume that user now decided to work with filter `B` and add `b2` value, so now selection is `(a1, b2`). Using our idea, we will not reload values for `B`, but will reload `A` and `C` using selection: `A {a1}`, `B {b1, b2}`, `C {c1}`. But we missed something: since `A` has selected value, user can add more values to it without breaking logic. But now we have no values for `A` except of selected ones. New idea is to reload `A` using all selected filters except of values from `A`, in our example we'll use only `(b2)`. So we'll have `A {a1, a2}`, `B {b1, b2}` and `C {c1}` (notice that we have no `a3` filter value since it cannot be combined with `b2`).

This solutions allows to reduce amount of filter values based on other filters, and in the same time it is transparent for user and will never lead to a "deadlock" when user has only selected values (as naive solution reduces amount of filter values each time when user adds new filter value), cannot select anything else and does not know what to do with that.

Conclusion. Generic rule for reloading values for filter `X`:
1. make new selection excluding all values of `X` from selected set `S`: `S1 = S - {x1, x2, ... ,xn}`
2. load values using `S1`.
Possible optimization: all filters that have no selected values will have same `S1` set and it will be completely equal to `S`, so they could be loaded together (if API will allow that).

**Comment by kravets-levko** [comment]
@akariv Please read my comment above and I'd like to know your opinion about that.

**Comment by akariv** [comment]
Great suggestion @kravets-levko! Let's go with it.

Luckily the API we need is already available, see for example:
http://staging.openspending.org/api/3/cubes/a0f62a17e1fc9e6bea3e94a2f41fbba2:cameroon-trial/members/economic_classification_Level_2?cut=economic_classification_Level:%2261%22

**Comment by akariv** [comment]
We'd still need one API call per filter, but that's OK I think.
One important thing though is to make sure we're only refreshing _visible_ filters.

**Comment by kravets-levko** [comment]
Yes, definitely I'll do all possible to optimize code. Great news about API - it will not block me, so I can start right now

**Comment by kravets-levko** [comment]
@akariv Here is PR for this feature: openspending/os-viewer/pull/140
I performed a lot of checks on a several datasets; with a single pair of eyes it may take a human's life (and a barrel of coffee) to check all possible cases. So we'll need to collect as much feedback as possible.
