### ISSUE TITLE
Packager: Modelling status pane

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1131]
This is to get your creative suggestions.

Right now you have a list of cards that are more or less static. When lots of columns are available, it becomes really hard to work with this UI.

A possibly better approach is to somehow move each mapped (=processed) card into a logical place in the mapping. The mapping itself is actually a tree - each card has a type (e.g. `activity->program->generic->level1->label`). Different types interact with other types (e.g. the `labelOf` and `parent` relations). 

It could be nice to show processed cards in a logical view, and unprocessed cards in a sort of 'TODO queue'.

**Comment by DianaMPG** [comment]
estimate of 1 day to finish

**Comment by smth** [comment]
@akariv 

My first step towards this was the introduction of the TODO list and NOTGONNADO list [here](https://smth.github.io/os-mockup-packager/packager/describe-data/). In which list (or at which end of the single list) each card resides was to be determined by the user toggling a switch. The reason for adding a switch (which is [possibly undesirable](https://github.com/openspending/openspending/issues/1130#issuecomment-266388902)) was the assumption that there is no definitive measure of a "done" card, and so the only reliable way to determine when a card should be moved is to have the user make that distinction. (I opted for moving ignored cards, rather than complete ones, so it'd be easier to keep track of what you've done / are working on).

Is my above assumption correct? If so, we probably need to revisit the idea of some sort of user action for marking a card as done. If not, what has to happen for the app to decide that the user is finished with a card, and should be moved?

To get to your specific suggestion: The idea is to:
- move cards once mapped (as opposed to ignored)
- order the mapped cards, based on their `Data Type`

Is that correct?

**Comment by akariv** [comment]
Okay @smth - 
Just thinking out loud here - perhaps we need to add a third list which is 'DOING'. 
Then the flow would be:
- Go over the TODO, and decide whether to ignore or to map to a type (that's the first step). I think that the switch for ignoring a card is not intuitive enough, and perhaps we could combine the ignore vs. map into one step.
Ignored cards are moved to the NOTGONNADO list, and mapped cards are moved to the DOING list.
There are some conceptual differences between the DOING and the rest of lists: 
- DOING is ordered by type and not by original column order
- DOING cards show all the user provided fields (i.e. description, currency etc.), while other lists could show more compact cards.

wdyt?

**Comment by smth** [comment]
That makes sense. So you'd have a step (before adding things such as name) where you either give a data type to or ignore the column. The idea here is that ordering the cards by data type will make adding additional info easier. Is that correct? Could you explain how so (I have no problem with this idea, but would like to understand it)?

**Comment by akariv** [comment]
Yes - 
for example, you'd like to show all columns that compose a single hierarchy together (e.g. 'Country', 'City', 'Street Address' etc.), in the correct order.
Some columns are the code and title for the same concept (e.g. 'Country code' & 'Country name'). We would like to group these two cards together.
Usually, columns in source files are (more or less) grouped like that (as it makes more sense to humans and machines alike). But it's not always the case.
Also, by grouping columns and separating groups, you provide more meaning than just the column order does.

**Comment by smth** [comment]
If we are going to reorder the columns, I can see that an order determined by hierarchy makes sense. Likewise, assuming that we are reordering, it seems logical to group columns together that form part of a single concept, but I'd like to understand the rationale in terms of this step. For example, are we then going to allow for a title/description that spans multiple columns/files? Or, is this a way of visually confirming that two columns will form a single concept?

I feel like I understand the solution, but would really like to understand the problem.

**Comment by smth** [comment]
I just took a little time to remind myself where I got to last time I was looking at this. I think it's worth sharing to get some feedback. I'd been working on an idea in which the first step of "describing" the data would be to go through each card in turn, and assign a "data type". This process would reorder and colour code the cards as you go. Once done, you are then free to edit titles and add descriptions, much as before. You can also revisit the data type interface for any card. Here's a pretty much static, and slightly rough mockup http://p.smth.uk/os-mockup-packager/packager/map-data/ It shows one assigned card (in the background) and one ready to be assigned. Hopefully it gives an idea of how it would work.

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/openspending/openspending/issues/1276
