### ISSUE TITLE
Viewer: Sorting should be done by the titles and not the IDs

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1134]
When a dimension has a title and a code/key/id, sorting should be done by the title (not the id)

**Comment by akariv** [comment]
Related to os-data/mexican-federal-budget#45

**Comment by kravets-levko** [comment]
@akariv (correct me if I'm wrong) - sorting issue described in https://github.com/os-data/mexican-federal-budget/issues/45 was about how data are displayed in Table - I noticed that sorting works well when sorting by selected measure, a bit strange when sorting by x-axis dimension. This sorting is performed by babbage API and I cannot affect it. If this task is about the order of dimensions in sidebar (or elsewhere) - then I need an example, because currently dimensions are already sorted using their titles.

**Comment by kravets-levko** [comment]
yep, I'm wrong :-) It is possible to use `label_ref` for sorting instead of `key_ref`. Will fix ASAP
