### ISSUE TITLE
OBEU blocker: When measure label differs from measure ref, some visualizations may fail

### ISSUE THREAD

**Issue by larjohn** [openspending/openspending#1140]
The following piece of code in src/api/index.js fails in OpenBudgets.eu, where the measure label is different from its ref for some measures. Currently, this is a translation issue, which if I am not mistaken, is already handled somewhat different in OS, so it might change in OBEU as well, but still, why use label when ref is available?

 _.each(measures, (measure) => {
          let measureModel = _.find(measureModelList, {'label': measure.value});
          result.summary[measure.key] = data.summary[measure.key];
          result.currency[measure.key] = measureModel["currency"];
        });

I have made a PR for this item, and it is working fine for us:
https://github.com/openspending/babbage.ui/pull/51

As it is a blocker for our release, can you review it ASAP?

**Comment by mlukasch** [comment]
@akariv @pwalsh Can you have a look at this please? Thanks.

**Comment by akariv** [comment]
Hey @mlukasch @larjohn 

The code is quite confusing as it does not separate a "measure" (i.e. a column in the database) from an "aggregate" (i.e. a measure + an aggregation function). That being said, from a static reading of the code this doesn't look like it has a bug.

This line:
```javascript
let measureModel = _.find(measureModelList, {'label': measure.value});
```
Is actually trying to find the measure model based on the matching the measure label (i.e. its display name) with the aggregate label. Using the `ref` would arguably have been better, but this will cause problems only if two measures have exactly the same display name. Is this the case in your setting?

The reason this works is that `measure` is an element of `measures` which in turn comes from this function (which actually returns aggregates and not measures, hence the confusion):
```javascript
  getMeasuresFromModel(model) {
    var result = [];
    _.each(model.aggregates, function(value, key) {
      if (value.measure) {
        result.push({
          key: key,
          value: value.label
        });
      }
    });
    return result;
  }
```
The resulting list of aggregates has `key` of the form `approved.sum` and `value` which is simply the label of the original measure. Therefore, searching by label actually makes sense here.

We can change the code to user the `ref` instead of the `label` property, but we'll  have to modify the `getMeasuresFromModel` as well. Either way, I don't think it will have any affect on the correctness of the implementation...

**Comment by larjohn** [comment]
True this is not an issue. I used the measure's ref as a label in the aggregate so it was a matter of time before it was not just "amount" to break everything.

Generally speaking ref would be better, but I would happily live with "if it ain't broken, don't fix it".
