### ISSUE TITLE
GIFT phase II Croatia: Testing datasets and and bug fixing

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1163]
This relates to #1162

**Comment by DianaMPG** [comment]
Incoming alterations of the uploaded dataset: 

Attached you can find the sample report with the changes in titles. Accordingly, the names of hierarchies should be changed (viewer - Hierarchies), as stated below:
 
Activity -> Program Clasification
Administrative Clasification -> Organizational Clasification
Date -> Date
Economic Clasification -> Economic Clasification
Fin. Source -> Funds
Functional Clasification -> Functional Clasification

- [ ] (Diana)

**Comment by DianaMPG** [comment]
2. change request

Goal: **equalize grand total to the one published in official budget document**

- those summary rows partially in columns with codes contain blank fields, and the titles columns content associated to them is: 'unallocated'  (if possible) or

- to have code fields filled with blanks, for those five (yellow) rows we can put some fictive codes

**Comment by DianaMPG** [comment]
Questions after call with team Croatia:

1. can the conversation rate be already included in the datasets considered for upload?

2. displaying the three approved budgets: According to OS team's experience (technical feasibility and user behavior) - what would be the best to present them - only one year at a time or all three according to the budget cycle?

3. Could be “change language” feature be included so that  Administrative, Economical and Functional 

@akariv ?

**Comment by akariv** [comment]
It would be best to split separate issues into separate issues. Otherwise it becomes very cumbersome to manage...

1. Translations - Done
2. change request - didn't get it

Questions:
1. Conversion rate is pulled from the European Central Bank (we use the one from January 1st on the fiscal year). We don't plan on using user provided conversion rates.
2. Is this a question about the best visualisation? It really depends on the narrative that you want to present to the users. There's no 'right answer' here.
3. Didn't get the question...

**Comment by DianaMPG** [comment]
@akariv will split the issues

**Comment by akariv** [comment]
Thanks @DianaMPG - please close this one once there are separate issues.

**Comment by akariv** [comment]
?
