### ISSUE TITLE
Clicking edit has no effect

### ISSUE THREAD

**Issue by Vanuan** [openspending/openspending#1185]
Reproduce:

1. Go to http://next.openspending.org/packager/provide-data/?...
2. Click edit

Expected:

new page opened

Actual:

nothing happens

**Comment by akariv** [comment]
@Vanuan - I can't see any edit button in the above link, can you re-paste it here?

**Comment by Vanuan** [comment]
Maybe there are differences in browser behavior? I'm using Chrome 57

**Comment by Vanuan** [comment]
Here's my theory:

1. `/admin` and `/provide-package` are different angularjs applications
2. when I'm on `/admin`, only `/admin` routes are tracked
3. when I click any link that points to another application (e.g. `/provide-package`), angular routes catch that route and prevent a new html page from being loaded

**Comment by akariv** [comment]
Cc @kravets-levko

On Thu, Jan 5, 2017, 19:36 John Yani <notifications@github.com> wrote:

Here's my theory:

   1. /admin and /provide-package are different angularjs applications
   2. when I'm on /admin, only /admin routes are tracked
   3. when I click any link that points to another application (e.g.
   /provide-package), angular routes catch that route and prevent a new
   html page from being loaded

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/openspending/openspending/issues/1185#issuecomment-270706023>,
or mute the thread

**Comment by Vanuan** [comment]
The "view" button works because it's opened in a new window.
