### ISSUE TITLE
OS Viewer: Bubble tree enhancement based on WP 3 D 3.5.

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1198]
D 3.5 of WP3 OBEU had as its aim to give recommendations on how the different visualization types could be enhanced so that they meet best best practice requirements in data visualization. J++ was in charge of this report that is publicly available:
http://openbudgets.eu/assets/deliverables/D3.5.pdf

The following recommendations can be found in the report:

***Bubble tree***

1. The use of colors
The colors can be used to add another dimension like the direction - revenue or expense - or the type of the money flow - operating or investment.
When the colors are used to represent a category, the click on a category (bubble) should display the corresponding subtree where all the bubble have the same color range as the main category.

**Comment by vitorbaptista** [comment]
There're 2 tasks here:

1. Use colors to represent revenue/expense or type of money flow
2. Keep a subcategory's colors the same as its parent category

The task 1 can get complex quickly. As far as I know, we don't have a way to allow our users to customize the charts, so we have to decide how they'll look like. This means that we're constrained as any change needs to work on all data we have. Do we have a way to know if a data point is a revenue or expense? Or some other dimension?

Task 2 is also tricky. Consider a dataset where we can drill down 4 times. The first time (no drill down) would get a colourful bubble tree. However, as soon as we drill down once, the entire chart will have a single colour, and the following drill downs will have to keep the same colour.

If we have enough information in the datasets, I'd suggest we only do the task 1.

**Comment by vitorbaptista** [comment]
ping @akariv @DianaMPG

**Comment by vitorbaptista** [comment]
@akariv @DianaMPG and myself talked about this issue. There are a few problems with using the bubbles colours as another dimension. Let's consider 2 cases: using colours to represent revenue/expense, and using colours to represent the categories (and subcategories would have the same colour as their parent category).

If we use colours to represent revenue/expense, say red for expense and blue for revenue, what happens if a bubble have children that represent both revenue and expense? Which colour would we use? Another colour entirely? A mix between red and blue? Even if a bubble has no children, maybe its value was calculated from both revenue and expenses.

If we use the colours to represent categories, say red for Healthcare, blue for Security, etc. In the first level of the bubbletree, we would have the colourful bubbles. Then, as soon as we drilldown to a deeper level, everything will become a single colour, including the levels below it.

Given all of this, I see three options:

1. Keep the bubbles as they are now;
2. Remove the bubbles' colours, as they don't represent anything;
3. Use 2 different colours to represent positive and negative values. Here we're not talking about revenues/expenses directly, just if the number is greater than zero or not. So a blue (positive) bubble can have red (negative) child bubbles when we drilldown.

Personally, I'd go for either option 2 or 3. What do you think?

**Comment by DianaMPG** [comment]
@vitorbaptista thanks for elaborating. 
I have a questions in regards to 2. 

2. would we only outline of the bubbles?

In regards to 3., a note: We currently don't have spending data but mostly budget data. That means only positive values are shown at this point.

**Comment by akariv** [comment]
Budget data also has negative values, as income assessment is part of the budgeting process in many cases.

**Comment by DianaMPG** [comment]
thanks @akariv for clearfication. 

Now - I think 3. could be useful. What do you think?

**Comment by DianaMPG** [comment]
Also @akariv @vitorbaptista 
I just got feedback from Nicolas from J++ : 

Thanks for getting this discussion going!

Point 1 (make colors dependent on a column) : The tool allows the users to describe the dataset and to give more info on each column, so we do have more details. But the "data description process" will probably change and be simplified so it's better to not work on this point now. It's very low priority, let's keep this for the very end

Point 2 (keep colors consistent in subcategories) : We were thinking about a behavior like the one described here : https://www.vis4.net/blog/posts/tutorial-bubble-tree/. But if it's technically complex, it might not be prioritary.

Point 3 (change color based on positivity): Probably the lowest hanging fruit, though we have rarely seen negative values in budgets. The use of negative values depends on the accounting practices of the administration, so there might be cases where it'll be useful.

-----

I would say lets opt for option 3.

**Comment by DianaMPG** [comment]
lets settle for option 3.

**Comment by vitorbaptista** [comment]
Agreed :+1:

**Comment by vitorbaptista** [comment]
There're still a few PRs to be merged

**Comment by vitorbaptista** [comment]
Fixed
