### ISSUE TITLE
OS Packager: edit function not working

### ISSUE THREAD

**Issue by skarampatakis** [openspending/openspending#1269]
I am trying to edit this dataset 

https://next.openspending.org/packager/describe-data?package=https:%2F%2Fs3.amazonaws.com:443%2Fdatastore.openspending.org%2Fdsome36f2db04a86c03bdf4448b1%2Feurope-greece-municipality-thessaloniki-2016-revenue%2Fdatapackage.json

but I get the following error on the console
```
Fetch API cannot load https://s3.amazonaws.com/datastore.openspending.org/dsome6c03…48b1/europe-greece-municipality-thessaloniki-2016-revenue/datapackage.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://next.openspending.org' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
I get just the theme but not the actual packager
![screenshot from 2017-05-30 19-17-592](https://cloud.githubusercontent.com/assets/2419820/26593839/2e49830e-456e-11e7-8f06-d5d8e4fde619.png)

using Chrome.

I don't get this error on another dataset I ve uploaded.

**Comment by akariv** [comment]
Seems that you're trying to edit this data package:

https://s3.amazonaws.com/datastore.openspending.org/dsome36f2db04a86c03bdf4448b1/europe-greece-municipality-thessaloniki-2016-revenue/datapackage.json

But when trying to open this link it points to nowhere - are you sure this
dataset was successfully uploaded?

**Comment by skarampatakis** [comment]
It is show on the OS Admin

![image](https://cloud.githubusercontent.com/assets/2419820/26620794/f13ffe32-45ec-11e7-92cb-0fdeb5afa610.png)

I have changed the hash so maybe that's the reason it is not pointing anywhere ATM. 

When I click on the edit button I get the view on my previous comment.

I have published the dataset so you can take a look. I still cannot edit. 

https://next.openspending.org/viewer/d95067fc436f2db04a86c03bdf4448b1:europe-greece-municipality-thessaloniki-2016-revenue?lang=en

**Comment by pwalsh** [comment]
@akariv can you please check this asap.

**Comment by skarampatakis** [comment]
I checked today and it seems to be fixed. I can now edit the dataset. Thank you!

**Comment by akariv** [comment]
Just my understanding of the issue:

So this is the link to the datapackage you originally tried to edit:
https://s3.amazonaws.com/datastore.openspending.org/dsome36f2db04a86c03bdf4448b1/europe-greece-municipality-thessaloniki-2016-revenue/datapackage.json

This is the actual link to the datapackage:
https://s3.amazonaws.com/datastore.openspending.org/d95067fc436f2db04a86c03bdf4448b1/europe-greece-municipality-thessaloniki-2016-revenue/datapackage.json

As you can see, it seems that the link was (manually?) edited and 'some'
appears instead of `95067fc4
<https://s3.amazonaws.com/datastore.openspending.org/d95067fc436f2db04a86c03bdf4448b1/europe-greece-municipality-thessaloniki-2016-revenue/datapackage.json>
`.
Since with 'some' the link becomes invalid, the edit functionality would
not work.

I'll open an issue to provide better indication to users in such cases.
