### ISSUE TITLE
How can I create a budget pie chart per city?

### ISSUE THREAD

**Issue by kgish** [openspending/openspending#1284]
Hi there, I would like to create an application which does the following:

1. Select a government by type, for example a gemeente.
2. Display the budget for that gemeente for a given year in a pie chart divided by top-level items.
3. Allow the user to click a given top-level item and zoom in.

Something very similar as the current openspending website allows but I want to gather all the relevant data myself.

I already have the select gemeente working fine (step 1), but cannot figure out how to query the budget related information.

Which API calls do I have to make in order to do step 2? For a given top-level item, how can go one level deeper to display the financial details?

Thanks alot in advance for helping me.

**Comment by akariv** [comment]
Hi @kgish,

Best way to get answers on such questions is via http://docs.openspending.org and https://gitter.im/openspending/chat. Issues are meant to be reports on problems, bugs or missing features.

To your question - see the `aggregate` api endpoint, you should be able to set the `filter` and `drilldown` parameters so that only data on a specific entity is shown, and grouped by the desired dimension.
