### ISSUE TITLE
Error while submitting dataset in local deployment

### ISSUE THREAD

**Issue by pierorex** [openspending/openspending#1287]
I'm getting the following error whenever I try to submit a dataset through OS-Packager. 
@akariv told me it might be something related to my installation using http://next.openspending.org instead of https://...
Where can I override that behavior? 

![image](https://user-images.githubusercontent.com/9373636/27957675-c867010e-631f-11e7-9e16-0b994e5b3418.png)

**Comment by kravets-levko** [comment]
Hi @pierorex! Did you try to use https://next.openspending.org instead of http://next.openspending.org ? HTTP version makes redirect to HTTPS, but browser cannot do it because HTTP version does not set required CORS headers (and since your installation makes request from another origin - CORS headers should be provided for every request, even for redirects). 

CC: @akariv Maybe, it makes sense to include CORS headers for HTTP too?

**Comment by akariv** [comment]
In openspending next HTTP is automatically redirected to HTTPS, so there's no CORS on a redirect.
The codebase only references the HTTPS endpoints, so if you have HTTP calls it's most likely because either your code is not up to date or you're using some environment variable that's overriding the default configuration.
