### ISSUE TITLE
Number/currency depiction in Viewer delivers false outputs (iframe)

### ISSUE THREAD

**Issue by seegerseeger** [openspending/openspending#1292]
Currently, describing German (or any other non-US currency) budget data using the OS Packager results in a false display of numeric values / currency formats in the Viewer and when embedded (see example below). This has been an issue for OffenerHaushalt.de as well as SubsidyStories.eu, and will be for other individual iterations using OS. 

Can this be addressed in the current redesign?

Live example: https://offenerhaushalt.de/haushalt/berlin2/ 
![image2](https://user-images.githubusercontent.com/9677965/28516455-9cc5c96e-7061-11e7-9610-db9220f93a57.png)

Issue in visualisation (iframe): 
* Currently it reads e.g. € 3230000001.17 Billions
* It should be “million, or billion” no “s” 
* It should either be 3.2 Billion or the whole number 3230000001.17 (without billion) 
* For a plausible German version, we would have to change the delimiter to a comma “,” instead of a dot “.” and set the currency symbol behind the number.

Introducing a thousand separator (varying by languages, could help): 
* English speaking world  “€3,230,000,001.17”
* German speaking “3.230.000.001,17€” 

**Solution?**
* Option in Packager to select currency format 
* Separate language file specifying currency format (perhaps the field descriptions / translations could be specified here as well?)
* Limiting after comma values? 
* Often does not make sense to show after comma values if you are viewing million/billion amounts
 
The same problem has been previously solved, however not on the OS level: 
https://github.com/openspending/subsidystories.eu/issues/40

cc @pwalsh @akariv @smth

**Comment by vitorbaptista** [comment]
@seegerseeger Thanks for your report. I checked [the data used by that visualization](https://next.openspending.org/api/3/cubes/a6a16b964a7e784f99adecc47f26318a:berlin20162017doppelhaushalt/aggregate?drilldown=administrative_classification_2.Einzelplan%7Cadministrative_classification_2.Einzelplanbezeichnung&order=amounts.sum:desc&pagesize=30), and the issue is with the source data itself. For example, if you follow the link to the data, you'll see things like:

```javascript
{
  "amounts.sum": 6443110228893010000,  // This is ~6.4 sixtillions
  "administrative_classification_2.Einzelplanbezeichnung": "Gesundheit und Soziales",
  "_count": 1084,
  "administrative_classification_2.Einzelplan": "11"
},
```

So the huge numbers are caused by the source data, not OpenSpending.

We then have the other problem of wrongly saying "3.2 Billion*s*", when it should be "3.2 Billion". I'll submit a PR for that after this. The bigger issue of localising numbers is something we need to do, but it's better to keep it as a separate issue from this IMHO.

**Comment by michaeljokf** [comment]
@vitorbaptista thanks! I am a colleague of @seegerseeger 
I will look into the data again in detail and see what went wrong. 

Thanks for fixing the plural of "billion". 
Yes I agree that localisation is a major task. However, I am not a developer so I not the most knowledgeable on this. Are there any plans to improve this? Should I make a new issue for it? 
Localisation would mean that delimiters and currency symbols could be changed right?

**Comment by pwalsh** [comment]
hey @michaeljokf you should open a new issue, yes.

I don't think it is related to currency symbols though - currency symbols should currently be based on the currency declared in the Fiscal Data Package.

**Comment by michaeljokf** [comment]
Thanks @pwalsh!  True, the currency symbols are separate. I was mostly thinking about the numbers format. We will get back to you guys on this. We have a new developer @aivuk who will help us with the implementation for offenerhaushalt.de. We will give you guys feedback on this once we have worked it out for Offener Haushalt.
