### ISSUE TITLE
Stop testing code using interpreter versions we don't use

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1302]
For example, on https://github.com/openspending/os-api we use Python 3.6 in production, but test using 2.7, 3.3, 3.4 and 3.5 (i.e. not 3.6). Unless we're developing a library that's supposed to be imported and used as part of another projects, we should support a single version: the one we use in production.

There are similar issues with other repositories, like https://github.com/openspending/os-viewer where we use Node 7 in production but testing using Node 4. We must go over all our repositories and make sure we're testing using the versions we're actually using.

**Comment by pwalsh** [comment]
@brew this is a maintenance one that is good to pick up just to give you a high-level view on all the components of the platform.

**Comment by brew** [comment]
It looks like @vitorbaptista has tackled most of the important libs for this issue. 

There are a few others that might need upgrading. This lists the reops that are either < py3.6 or < node 7.x, and I'm not sure if they should be upgraded, perhaps because they are used in other projects, are deprecated, or not used within the OS architecture. @vitorbaptista , please check the list and let me know which ones I should upgrade, or if the ticket can be closed:

- [ ] [os-cli](https://github.com/openspending/os-cli)
    py27
    py33
    py34
    py35

- [ ] [os-api-cache](https://github.com/openspending/os-api-cache)
    travis:
     2.7
     3.3
     3.4
     3.5

    tox:
    py35

- [ ] [os-auth-client](https://github.com/openspending/os-auth-client)
    package.json: "node":
    ">=0.8.0"
    
    travis:
    node_js: ["0.10"]

- [ ] [cosmopolitan](https://github.com/openspending/cosmopolitan)
    2.7
    3.5

- [ ] [os-package-registry](https://github.com/openspending/os-package-registry)
    py27
    py33
    py34
    py35   

- [ ] [babbage.ui](https://github.com/openspending/babbage.ui)
    travis: "4.1.2"

- [ ] [os-conductor](https://github.com/openspending/os-conductor)
    travis:
    py3.5

    package.json: 
    "node": "^4.1.0",

- [ ] [os-fdp-adapters](https://github.com/openspending/os-fdp-adapters)
    py3.5

- [ ] [babbage](https://github.com/openspending/babbage)
    py27
    py34
    py35
    py36

- [ ] [gobble](https://github.com/openspending/gobble)
    py33, py34, py35

**Comment by vitorbaptista** [comment]
* `os-cli` - I'm not sure if this is still used, as it sounds very similar to `gobble`
* `os-api-cache`, `os-auth-client`, `os-package-registry`, `os-fdp-adapters`, `os-conductor`, `cosmopolitan` - They're all internal-only AFAIK, so we should only support what we use
* `babbage.ui` - Although this can be used independently from OpenSpending, I'm happy to support only the NodeJS version we actually use
* `babbage`, `gobble` - Sounds correct. We can drop `py33` and add `py36` to `gobble`, if py36 doesn't break anything

@akariv Does this sound sensible?

**Comment by brew** [comment]
@vitorbaptista re: gobble, The readme suggests support for 3.3, 3.4, and 3.5, and in the future, 2.7. Currently, the codebase uses `from json import JSONDecodeError` which isn't supported in 3.3 and 3.4 (it was introduced in 3.5). This can be fixed by using `ValueError` instead. However, perhaps we just want to drop support for these versions (3.3, 3.4) that never actually worked in the first place. And remove the reference in the readme to support Python 2.7 in the future, which I can't see happening. WDYT?

**Comment by pwalsh** [comment]
As discussed at standup: just go for latest pythons.

**Comment by brew** [comment]
The major libs have been upgraded, and various fixes for travis/coveralls added, where appropriate. 

I think enough has been done here to consider this close.

wdyt @vitorbaptista @pwalsh

**Comment by vitorbaptista** [comment]
Agreed. Closing the issue, but (as usual) feel free to reopen.
