### ISSUE TITLE
Views of data packages with positive and negative numeric value measures

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1319]
# Description

Some data packages loaded to OpenSpending have positive and negative values in the same direction (e.g.: a negative expenditure). Some visualisation types need to know this, as, they simply will not work with such data (e.g.: a treemap).

# Tasks

- [ ] Pre compute a flag on the API to say "this data package has records with mixed positive and negative values"?
- [ ] Use above flag (or similar) to enable/disable some vis types in the viewer
  - e.g.: treemap

Thoughts @vitorbaptista @akariv

**Comment by vitorbaptista** [comment]
We implemented different colours for the bubble tree on https://github.com/openspending/openspending/issues/1198 (but I found a bug on it https://github.com/openspending/openspending/issues/1322). We could do the same for the treemap, but it's kind of stretching the meaning of the visualizations.

Instead of thinking about treemaps, it's easier to think about pie charts. Both treemaps and pie charts show parts-to-whole ratio, the difference being on how the information is encoded in the graphs. So, the entire pie represents 100%, and each slice a different percentage. When we mix positive and negative values, we break this assumption. We have to consider the absolute values when building the pie, so then the whole pie represents the sum of the absolute slice's values. This can easily mislead the viewers.

I think the correct solution here is to, as you suggested:

* Disable visualizations that don't handle mixed positive/negative values;
* Allow datasets with negative-only values (might be unecessary, as the values could be transformed in positive)

**Comment by pwalsh** [comment]
@vitorbaptista 

Any ideas on how difficult this might be to implement?

**Comment by vitorbaptista** [comment]
@pwalsh I'm not sure. It seems like it should be added somewhere around https://github.com/openspending/babbage.fiscal-data-package/blob/09c41506a8b7d70448fc6c6bb5f3efb41ee65630/babbage_fiscal/loader.py#L126, but I don't know enough about the FDP loading process to be able to estimate this without diving deeper. @akariv?

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2.5 years) as part of #1478. Please feel free to re-open if this is still relevant.
