### ISSUE TITLE
Redash (DataMine) unavailable on K8S (default backend - 404)

### ISSUE THREAD

**Issue by florent-andre** [openspending/openspending#1364]
When I click on "Analyse this data set in the Data Mine", this message appear : 
"default backend - 404".

Example : 
https://rd.openspending.org/queries/new?queryText=SELECT%20*%20FROM%20fdp__74ad33ef9a3354fe__budget_mairie18__154e9c63%20LIMIT%2010&focusedTable=fdp__74ad33ef9a3354fe__budget_mairie18__154e9c63&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyaWQiOiI3NGFkMzNlZjlhMzM1NGZlNjc5Yjc5ZmU0YWNjZmYxMiIsImV4cCI6MTUyOTczODE5OH0.WruGhziZzig7yv8UohIo9Bgo5lHtDGtbViaK31k6kWk

Thanks.

**Comment by brew** [comment]
Thanks for the report @florent-andre. We'll be taking a look at this, and using this ticket to track the issue.

**Comment by brew** [comment]
Redash, used by OpenSpending as the 'Data Mine' component, has been unavailable since the kubernetes migration. It should be available at https://rd.openspending.org. 

`default backend - 404` usually means there are no ingress rules in place for the domain. Either because the app isn't set up at all, or it is misconfigured.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) nor assignee as part of #1478. Please feel free to re-open if this is still relevant.
