### ISSUE TITLE
Concatenate Assertion Error

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1380]
Hi, I got the [concatenate assertion error](https://openspending.org/package/status?datapackage=https://s3.amazonaws.com:443/datastore.openspending.org/5537104a902b0847bb7b474225eced5a/test/datapackage.json) while uploading the same csv file as in https://openspending.org/viewer/5537104a902b0847bb7b474225eced5a:merzenich2013slim2?lang=en .

**Comment by liyakun** [comment]
Hi, the following is a screen shot of the issue:

![image](https://user-images.githubusercontent.com/7370334/43524345-5494f1f6-959f-11e8-8c41-1e60526b31c5.png)

**Comment by brew** [comment]
@liyakun We made some changes to bring the datapackages produced by os-packager up to FDP v1 specification[1][2]. This resulted in two main changes for fiscal.source-spec.yaml definitions:

1) `osType` property is now `columnType`
2) `:code:full` and `:code:partial` properties are now just `:code`

Because you're using a custom packager frontend, which pre-defines columnTypes (https://github.com/openbudgets/os-packager/pull/3), it's likely these predefinitions will need to be updated.

---

[1] https://github.com/openspending/openspending/issues/1314
[2] https://frictionlessdata.io/specs/fiscal-data-package/

**Comment by liyakun** [comment]
@brew thanks a lot, after updating to new package format, the issue is solved.
