### ISSUE TITLE
Replacing a datapackage where column names change doesn't correctly update model in Elasticsearch item

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1403]
I sometimes need to upload a datapackage again because I named the measure column something which my app doesn't expect.

## Expected outcome

It looks like I can replace the datapackage by giving it the same ID in OS Viewer. I expect by selecting a new file, mapping columns to types and uploading to the old OD, it will completely replace the old datapackage and the measure field name will be fixed

## Actual outcome

It looks like the upload works fine but aggregate queries result in the following server error

```json
{"status": "error", "message": "Column 'amount' does not exist on table 'b9d2af843f3a7ca223eea07fb608e62ac1f8d2c2d0914708'", "context": {"table": "b9d2af843f3a7ca223eea07fb608e62ac1f8d2c2d0914708", "column": "amount"}}
```

In this case I renamed the column `amount` to `value`

## Steps to reproduce

1. Upload a dataset using OS Viewer
  - Keep the window open - I'm not sure whether the same would happen if you start from scratch and just give it the same ID again - I think it would
2. Click on Step 1
3. Upload a file with the measure column name changed
  - perhaps same issue for other columns
4. Use the same ID when naming the datapackage and upload.

here's one I prepared earlier :)
https://openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a:epre-sub-programme-expenditure-2017-18/facts/?pagesize=20

**Comment by brew** [comment]
Looks like saving a new datapackage with the same name as one that already exists within the Elasticsearch index will **update** the item, rather than replace it. This can be seen by making a request to the `/model/` endpoint for the dataset:

https://openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a:epre-sub-programme-expenditure-2017-18/model/

This shows in the `model.measures` property an item for both `amount` and `value`.
