### ISSUE TITLE
Failed to load data from https://openspending.org/package/status?datapackage=https%3A...datapackage.json

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1413]
Sometimes when uploading data using Packager, I get the following error:

```
Error: Failed to load data from https://openspending.org/package/status?datapackage=https%3A%2F%2Fs3.amazonaws.com%3A443%2Fdatastore.openspending.org%2Fb9d2af843f3a7ca223eea07fb608e62a%2Fadjusted-estimates-of-national-expenditure-2016-17%2Fdatapackage.json
```

![openspending-failed-to-load-datapackage-status](https://user-images.githubusercontent.com/235801/48952303-65d6e280-ef4a-11e8-8486-fc2ebf729d61.png)

Last time this happened I managed to upload it a couple of days later so I thought the issue was fixed, but it happened again this afternoon.

**Comment by jbothma** [comment]
Getting "failed" even though the response at that URL is
```json
{
  "progress": 0,
  "status": "loading-data"
}
```

![openspending-packager-failed-loading](https://user-images.githubusercontent.com/235801/49076703-4ab5ec80-f242-11e8-8d2c-86fee95777e8.png)

**Comment by jbothma** [comment]
Looks like the dataset was created after all on friday https://openspending.org/viewer/b9d2af843f3a7ca223eea07fb608e62a:adjusted-estimates-of-national-expenditure-2016-17?measure=%22value.sum%22&rows%5B%5D=%22voteno.voteno%22&columns%5B%5D=%22finyear.finyear%22&columns%5B%5D=%22budget_phase.budget_phase%22&columns%5B%5D=%22fy_descript.fy_descript%22&order=%22value.sum%7Cdesc%22&visualizations%5B%5D=%22PivotTable%22&lang=en

**Comment by otterbotter** [comment]
Experiencing the same issue now - unable to upload any datasets at the moment.
Tried with 2 different datasets - always get the same error back.

Any idea what might be causing this / how to work around it?

**Comment by otterbotter** [comment]
> @otterbotter Can you give me a link to the dataset data, so I can try?

Hi Brew - sure, here's the CSV I'm trying to upload: 
https://s3-eu-west-1.amazonaws.com/manual-uploads.vulekamali.gov.za/are/processed/are201718.csv

**Comment by brew** [comment]
@otterbotter (cc @jbothma) Thanks. I can see from the logs that this dataset is still being processed. So, although you get this error saying it's failed, eventually, this dataset should finish processing, and appear in your /admin list. If there is a queue of jobs to process, sometimes uploading can take a while. I've increased resources for the processor, so hopefully it should clear sooner.

Note for me:
We write upload progress status to a key/value store (Redis). I think what's happening is, this key expires before upload is complete (I thought the timeout was being renewed, but possibly not), so when the frontend requests progress status, the server returns Not Found (because the progress status storing key isn't there any more), and it looks like the whole thing has failed.

**Comment by otterbotter** [comment]
I can see that they have appeared in our admin panel as you suggested.

Thank you for looking into this and getting back to me so quickly @brew

**Comment by jbothma** [comment]
I think I got the same error for `adjusted-estimates-of-national-expenditure-2015-16`. I assumed it's the same error, but the dataset never showed up. trying to upload again.

**Comment by jbothma** [comment]
Reliably being able to upload data is really important for us to move quickly and keep to the schedule we have of releasing fiscal data.

I imagine it's difficult to ensure that all the parts of the system that need to work together don't get broken accidentally by an update, and it's probably frustrating to discover that something was broken several days after that work and having to come back to it.

I'd like to suggest a daily automated test that actually uploads a small dataset via packager to the production system, waits an hour or so, then checks that it's actually available and working properly.

I'm happy to put this together if you're ok with me doing that. I think a couple of cron-based "builds" on Travis-CI using selenium would do the trick.

There could be a third one that cleans up old datasets.

Does this sound alright?

I think what we'd get out of this discover early in the day if something was accidentally broken the previous day. This won't catch all issues, but it should catch the most serious problems.

**Comment by jbothma** [comment]
Done https://github.com/openspending/openspending/issues/1417

**Comment by brew** [comment]
I've pushed some changes which should resolve the two factors that make up the 'progress status error'.

- no progress being shown by the progress bar for 'loading into the database'
- an error when loading large datasets caused by too-short redis key expiration time

See the commits for details:
- https://github.com/openspending/os-conductor/commit/036701d448adb24bbef5c2c6a0f96b26ca662cd6
- https://github.com/openspending/os-packager/commit/e0a095cadd92cc15c3ffaa52f9253012ec33f883

The changes in os-conductor:
- increase the redis key expiration timeout to allow long-running processes to run, then write status to the key, without the key expiring. 
- fix status reporting to be a meaningful measure of progress through the total processing steps

Previously, progress was measured as the number of rows processed compared with the total rows. This was disabled as changes to the fiscal datapackage processor made that reporting inaccurate; some processors would work with a small number of rows, i.e. the year processor, and some would denormalise the dataset into many rows.

Instead, I'm now measuring progress as the number of processor steps reporting as successful, compared to the total number of expected steps. Note, the total steps is currently hardcoded, and any changes to dpp-fiscal may need to also be reflected in the number of steps hardcoded in os-conductor. Ideally, we'd be able to have dpp-fiscal report the number of steps it will undertake as part of the status call back function.

**Comment by jbothma** [comment]
Awesome - thanks @brew!

**Comment by otterbotter** [comment]
Thanks @brew 

I've noticed that the progress seems to go over 100%, up to 200%

Screenshots for reference:
![200](https://user-images.githubusercontent.com/7869992/52119202-0a4b6400-2621-11e9-9424-057273172f7c.PNG)
![177](https://user-images.githubusercontent.com/7869992/52119203-0a4b6400-2621-11e9-8b63-b6e0763edba3.PNG)
![133](https://user-images.githubusercontent.com/7869992/52119204-0ae3fa80-2621-11e9-93e9-890c77fca1ff.PNG)

**Comment by brew** [comment]
@otterbotter Extra Super progress! Is that the same dataset you posted as an example [in December](https://github.com/openspending/openspending/issues/1413#issuecomment-444827588)?

**Comment by otterbotter** [comment]
@brew This is a different dataset - though it did succeed in uploading, and the progress bar did eventually tell me that it was successful - which is nice!

Here's the dataset for reference: http://datastore.openspending.org/b9d2af843f3a7ca223eea07fb608e62a/nat-are-2014-15/final/data/are-2014-15.csv

**Comment by brew** [comment]
@otterbotter I've opened a new issue for this: #1421.
