### ISSUE TITLE
Error loading data on OS 

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1419]
Mexico City Government uploaded a new budget data file and mapped it through the Packager. The upload worked but now they're getting different errors, although the data package json is actually uploaded, as well as the CSVs. 

- First, when they tried to create the data package they got an error similar to what they used to get with the Federal files. This error was usually fixed by closing the app and opening again. This fix isn't working for them now

![screenshot 2019-01-14 13 03 11](https://user-images.githubusercontent.com/5587545/51147749-11046980-1821-11e9-97a4-ff1429b56fd8.png)

- When trying to access the file from the user dashboard, they get this error. 
![screenshot 2019-01-14 13 35 05](https://user-images.githubusercontent.com/5587545/51147678-cf73be80-1820-11e9-8446-c531d0f388ed.png)

It seems like the the file is actually uploaded and it can be downloaded from the datastore at http://datastore.openspending.org/4bf66b4263cfb77579f8a4d9dc6c892a/presupuesto_cdmx_2018/final/datapackage.json
- When trying to access it from the Viewer, they get this error related to the file.  As you can see in the screenshot, the CSV can be accessed as well if downloaded directly.

![screenshot 2019-01-14 13 39 49](https://user-images.githubusercontent.com/5587545/51147784-36917300-1821-11e9-82a4-55275ddd434a.png)

**Comment by brew** [comment]
Thanks @tlacoyodefrijol . 

The first error looks like the problem we have where the upload status is being misreported as broken. This is a known issue: https://github.com/openspending/openspending/issues/1413

The second issue with 'No data to display': It would be useful to have the exact url used that returns this page.

**Comment by tlacoyodefrijol** [comment]
This is the URL with the "No data to display" error. The dataset is private for now, will you still be able to see the content?

https://openspending.org/viewer/4bf66b4263cfb77579f8a4d9dc6c892a:presupuesto_cdmx_2018?lang=en

**Comment by brew** [comment]
@tlacoyodefrijol The first point here should now be fixed. See https://github.com/openspending/openspending/issues/1413#issuecomment-458630079 for details.

**Comment by tlacoyodefrijol** [comment]
@brew Luis shared the complete URL https://openspending.org/viewer/4bf66b4263cfb77579f8a4d9dc6c892a:presupuesto_cdmx_2018?measure=%22monto_aprobado.sum%22&groups%5B%5D=%22programa_presupuestario.programa_presupuestario%22&order=%22monto_aprobado.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en

**Comment by brew** [comment]
Replied to Luis by email with below:

---
I've had a look at the data file you provided (https://drive.google.com/file/d/1baqhOxEMnDpF-N1PUXpibbjLYOoStb-g/view?usp=sharing), and realise why you had errors during the upload. There were two problems, one a bug with os-packager, and the second duplicate rows in the data.

1) The bug with os-packager was causing progress to stop reporting when using the packager interface, and you would eventually receive the error 'Failed to load data from...'. Usually what happens is the datapackage is created successfully, and the error goes away.

2) However, because the data has duplicate rows, there is another error, which doesn't get reported, so we don't know the second error occurs.

We have fixed the first issue, so progress should report without error until successful completion of the upload. And if there is an error, this error should now be reported in os-packager, making it easier to fix the data problem (in this case, duplicate rows). 

So, each row of the data file should be unique with regard to the Primary Key columns (the classifiers). In this case:

          "CICLO",
          "GOBIERNO_GEN",
          "SECTOR",
          "SUBSECTOR",
          "UNIDAD_RESPONSABLE",
          "FINALIDAD",
          "FUNCION",
          "SUBFUNCION",
          "AREA_FUNCIONAL",
          "PROGRAMA_PRESUPUESTARIO",
          "FUENTE_FINANCIAMIENTO",
          "ORIGEN_RECURSO",
          "CAPITULO",
          "CONCEPTO",
          "PARTIDA_GEN",
          "PARTIDA_ESP",
          "TIPO_GASTO",
          "PROYECTO_INV"

Each row should collectively be unique for these columns.

I attached a file that I generated with duplicates removed. If you're interested, this is the python script I used to generate the file: https://gist.github.com/brew/7d3297eafdbb728cb86aef97f5ce4652

---

**Comment by brew** [comment]
Continue to work on resolving duplicate composite keys in data. Luis would like to preserve the duplicate values by aggregating them into one row. I'm working on this with a different script to above:

https://gist.github.com/brew/813706202385c79009e18e39dc39b0ed
