### ISSUE TITLE
Initial openspending visualisation is now only blue

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1428]
When loading a budget dataset, the tree visualisation used to have multiple colours for the categories. It changed to all blue. We got a request to review the possibility of returning to multiple colours for the treemap. 
<img width="1406" alt="screen shot 2019-03-07 at 09 48 02" src="https://user-images.githubusercontent.com/5587545/53969487-802e6980-40be-11e9-9afb-87451683500a.png">

**Comment by brew** [comment]
I believe using one colour was a deliberate choice. See https://github.com/openspending/openspending/issues/1196 for details.

**Comment by tlacoyodefrijol** [comment]
I see. The report mentions "The use of colors
Colors of the boxes can be used to measure a performance or a change, such as growth over
time. If it’s not the case, color ranges should fit the data in for instance using different shades of
one color."
Is it possible to at least implement shades of the colour and maybe different colours for different stages of the buget?

**Comment by jobarratt** [comment]
Please see comment here from Lorena:

I see that there is a report upon which the treemap was changed to all blue mentioned on the Github thread. From experience, in Mexico we stopped displaying the treemap as soon as it stopped having appealing colors, and from these months seeing the reactions when we present the viewer in all blue at events, the people in the room are unimpressed, since they compare with other tools that make treemaps. Please let us not just use shades of one color, but choose appealing colors (as Sander said, we lost the eye candy), the color palette we have for GIFT is quite varied and could be a nice option.

**Comment by jobarratt** [comment]
@tlacoyodefrijol do we have brand guidelines for GIFT to hand?

**Comment by LorenaGIFT** [comment]
Should we open a new thread for the bubbles graph? That one is still blue.

**Comment by akariv** [comment]
@nightsh can you add a screenshot of how it looks after the fix?

**Comment by jobarratt** [comment]
Hi Lorena, This is done https://github.com/openspending/os-viewer/pull/184

**Comment by nightsh** [comment]
@akariv 
![image](https://user-images.githubusercontent.com/1579997/58099170-cb4b1980-7be3-11e9-9705-6f2f4d2a8e04.png)
