### ISSUE TITLE
datapackage.json failed with error "Failed to load data"

### ISSUE THREAD

**Issue by schlos** [openspending/openspending#1481]
Publishing status:
datapackage.json - Failed
Error: Failed to load data from https://openspending.org/package/status?datapackage=https%3A%2F%2Fs3.amazonaws.com%3A443%2Fdatastore.openspending.org%2F6f9de6393bf997134dc1afbb45096b76%2Fhr-01%2Fdatapackage.json

![Screenshot 2020-07-05 at 16 05 48](https://user-images.githubusercontent.com/1014134/86534567-967a4e80-bed9-11ea-8f3d-3e2f890127da.png)

Dataset to reproduce (mapping as per screenshot): https://drive.google.com/file/d/1J2c-I_toDF8eaGhkXxHFiVinEU1GVD4h/view?usp=sharing

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing issue as part of #1478. Data will be migrated to the DataHub platform. Please feel free to re-open if this is still relevant once the migration has been done.

**Comment by schlos** [comment]
@sglavoie do I need to do anything with my dataset? How will move to DataHub resolve this issue? Could you share a more detailed resolution description?

Thanks!

**Comment by sglavoie** [comment]
@schlos, thank you for following up. I do not have a clear answer at this moment because DataHub is a completely different platform and we still have to define what will be merged and how exactly. We will focus on using DataHub, therefore I cannot say what will be fixed or not from the point of view of the OpenSpending platform, but it should be irrelevant in the end once we get all the desired functionality on DataHub and that OpenSpending is merged into it. In the meantime, one can publish data on DataHub in the following way, which should remain the preferred option: https://datahub.io/docs/getting-started/publishing-data

Note that you can publish publicly, privately or in an unlisted way. The easiest path to get started is to log in with a GitHub or Google account if you are interested in trying it out already. I hope that helps until we resolve the situation with the migration :slightly_smiling_face:.
