### ISSUE TITLE
Implicit limit to file size of uploaded CSV

### ISSUE THREAD

**Issue by danfowler** [openspending/openspending#923]
I'm running into a size limit of around 200MB for a single file uploaded through the packager.  During Step 2, no columns appear for modeling.  Looking in the console during Step 2, I find this:

![screen shot 2016-04-05 at 17 35 37](https://cloud.githubusercontent.com/assets/772616/14310104/d22d8eb4-fbe8-11e5-80f6-ca0ad2fe6cf0.png)

I'm using the latest Firefox.

**Comment by pwalsh** [comment]
@danfowler can you check on Chrome? We are not explicitly supporting firefox right now. Of course we want to, but we developed on chrome and are using some quite advanced browser features, so we need to check each browser.

**Comment by danfowler** [comment]
@pwalsh OK, I just checked on Chrome with [this source file](http://datastore.openspending.org.s3.amazonaws.com/405f5e1681d4b6673fbfc0ceb196fe47/boost-peru-2014/out.csv) (246.6 MB).  I could get all the way to Step 4.  Firefox was actually able to upload the CSV & `datapackage.json` and load into the database, but latest Chrome only manages to upload the `datapackage.json` before crashing with an "Aw, Snap!" error.

**Comment by akariv** [comment]
In the packager: 
Let's operate on the first X MB of the file (local or URL), and rewrite the upload so that it reads directly from the source and not from a memory buffer.

**Comment by kravets-levko** [comment]
@akariv Packager is reading entire file to save app state between page reloads - it's not possible to save File object, so it reads and saves contents of file (when uploading from hard drive - otherwise it saves only URL). If we'll load only part of file - it may break the `Publish` button on step 4

**Comment by pwalsh** [comment]
test.

**Comment by akariv** [comment]
@kravets-levko the idea is somehow to save the state without having to load the entire file to memory.
e.g. for 'load from URL', we can obviously save the URL and then stream-upload it when needed.
for 'load from file', we probably need a more creative solution - e.g. if we didn't reload the page, then simply use the File object. Otherwise, ask the user to re-select the file (and make sure it's the same one by comparing the first few bytes or similar)
