### ISSUE TITLE
OS-Viewer sidebar

### ISSUE THREAD

**Issue by larjohn** [openspending/openspending#930]
In the OS Viewer sidebar, when the series list is visible one can see the dimensions with their attributes. The attributes labels are not used, instead the column properties are used, and they are sometimes not that user-friendly.

**Comment by cecilaki** [comment]
Yes. True and agree. I don't remember what was the decision behind not using the attribute labels.

**Comment by akariv** [comment]
There was no decision - the reason is that the OS Packager currently does
not allow defining the labelFor relation between attributes, so you cannot
specify both label and code attributes as belonging to the same dimension.
Once the packager adds this property (in the next upgrade or the one after
that), the viewer will make use of it as you'd expect.
