### ISSUE TITLE
Column data type interaction improvements

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#970]
- Change data type 'codes' into more understandable names (e.g. `label` -> `Display Name`)
 - Add descriptions for each type
 - Group similar types together under a 'group title'
 - Order types by a natural order (not alphabetically)
 - Make sure that data elements can be cast based on the user's selection
 - Add missing types based on BOOST datasets

**Comment by cecilaki** [comment]
How does that relate to #854 ? 
( what was fixed in #854 then? )

A few questions:

- Change data type 'codes' into more understandable names (e.g. label -> Display Name)
Where would that be, here? 
<img width="297" alt="capture d ecran 2016-05-09 a 12 09 40" src="https://cloud.githubusercontent.com/assets/6681719/15110066/11b4dc3a-15df-11e6-9f74-cecbc0600aa7.png">

- Add descriptions for each type
Where would those descriptions be? 

- Group similar types together under a 'group title'
What would those groups be? 

- Order types by a natural order (not alphabetically)
Is that the 'natural' order? 
By 'natural', you mean the order mostly found in the budget files headers from left to right? 

date
administrative-classification
functional-classification
economic-classification
activity
administrator
procurer
supplier
recipient
direction
phase
geo-source
budget-line-id
invoice-id
value

- Make sure that data elements can be cast based on the user's selection
How does that reflect visually/technically?

- Add missing types based on BOOST datasets
What are they?

**Comment by akariv** [comment]
- This is mostly based on suggestions made by @VictoriaVlad, which I'll paste here later. These include the groups, descriptions and ordering of data types.
 - Visually I still need to see what's both easy to implement and makes sense from a UX point of view. After we get a feeling of how this dropdown works with this extra information, we'll decide on next steps (e.g. better design, add/remove information, change interaction entirely etc.)
 - If data type selection does not apply for the data in the column, an error message will appear at the bottom of the card (similar to how the 'Data type is incomplete' warning appears now).
 - BOOST datatypes are, for example, financial source and expenditure type, as well as 5th and 6th levels for economic classifications. I'll probably find more as I go along.
 - (and #854 talked about the now non-existent data-type selection - e.g. integer, string - so not really to this issue)
