### ISSUE TITLE
OpenSpending.org Landing page definition of structure and content

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#984]

**Comment by cecilaki** [comment]
I'm confused, what's the difference with #1000 ?

**Comment by akariv** [comment]
This issue is for a spec for the next OpenSpending homepage, including content and design.

**Comment by akariv** [comment]
Mock from @cecilaki:
![3075b97c-2260-11e6-879e-77f16812974b](https://cloud.githubusercontent.com/assets/265333/15533910/43e43bb4-226f-11e6-9d95-ef5079dcb547.png)

**Comment by akariv** [comment]
I really like it! 

A few small comments:
- "Join the community" - I would change the emphasis to be "about our community" and not the communication channels (for which we can have small links at the bottom of the text).
- The row of boxes (starting with "Standard & Tools") - what does clicking each box supposed to do?
- "Upload data and use open spending" - Focus on readers ("explore your government's budget") and not on publishers ("Upload Data"). Generally speaking, "upload data" can be added to the link in the top as it's a non-common use case with converted users which doesn't require so much screen real-estate.
- On the other hand, putting "gallery" on the top pretty much ensures that no one will ever click it...

cc: @annafralberts

**Comment by cecilaki** [comment]
_**> The row of boxes (starting with "Standard & Tools") - what does clicking each box supposed to do?**_

They're supposed to link to a page that lists all resources, stories, projects and applications that relate to those topics. Like in the [OpenData handbook](http://opendatahandbook.org/resources/#policy)
Right, @annafralberts ?

**Comment by akariv** [comment]
It's quite confusing to me I think as the titles 'Open Spending Projects', 'Open Spending Stories', 'Resources' etc. pretty much serve the same purpose, no?

**Comment by annafralberts** [comment]
Love it! Wouldn't change a thing.

@akariv, I am responding a bit more extensive to your comments because what I liked so much about this mock up was exactly that it represented the richness of Open Spending. But @pwalsh do let us know if we talk in circles again ;)

So here we go: 

>> "Join the community" - I would change the emphasis to be "about our community" and not the communication channels (for which we can have small links at the bottom of the text).

I would leave "join the community" as it is with links to the communication channels. That is where the community lives, I don't see a reason to hide the discuss forum somewhere underneath. That is in my view the problem with the current landing page, that the actual community and its pages was so deeply hidden. An about page about the "community" is just as effective as just seeing what the latest discussions and introductions where about. 

>>The row of boxes (starting with "Standard & Tools") - what does clicking each box supposed to do?

These are overarching categories, that bring the collection of the different Projects/Resources/Stories etc. together on particular topics (from more tech-categories standards and tools, to more content-driven categories as, procurement, aid, or Europe). This is different than scrolling down because then you would have to find everything about the EU in the different projects, stories, and resources. It is meant to provide a different entry point. 

>>"Upload data and use open spending" - Focus on readers ("explore your government's budget")

This would make sense if we had indeed so many government's budgets that changes are high you will indeed find your government's budgets, otherwise it is a bit an empty promise leaving readers with little results. So that might be our strongest use-case, but better served by providing links and displays for all kind of local instances of open spending/independent projects for budget transparency on national and local level. This is where actually comprehensive datasets are actively brought together and paired with context and analysis.  I wouldn't bring the data these platforms back in OS, I would say leave it there and link. So that is why the first thing that you can do with data at OS is rather uploading than reading. 

And your last question, difference between projects, stories, resources. @cecilaki  let me know if you had the same in mind: 
Projects: the local projects/websites etc. I just spoke about, offener haushalt, sinar projects, openspending.nl, open spending kosovo, red-flags (on the website we can just feature one and change them randomly). 
Resources: reports and knowledge we created about financial transparency at large, reports, guides, etc. FE. the how does the EU spends its money, to the visualisation collection etc.
Stories: stories created with financial data (different from Projects in the sense that these are smaller, and focus on one dataset where viz, and analysis is already done, kind of example cases).

**Comment by akariv** [comment]
Thanks @annafralberts for your comments.

Re the community - the current wording doesn't answer the two simple questions "what is the community" and "why should I join it". Newcomers to openspending.org won't press any links to any community that they don't know anything about.
Re the middle row of boxes - Got it. I guess we should wait with it until we have enough content to actually warrant such a filtering feature.
Re 'Upload data and use open spending' - we have data from 76 countries (according to openspending.org), which is quite a lot. On the other hand, if I were to judge what openspending does by the current mock, the only 'feature' OpenSpending has is uploading data...

**Comment by pwalsh** [comment]
Re the community - the current wording doesn't answer the two simple questions "what is the community" and "why should I join it". Newcomers to openspending.org won't press any links to any community that they don't know anything about.

+100

**Comment by annafralberts** [comment]
> community
Good one, let's add a "why join" and 'we need you for open spending' (imagine Uncle Sam :)) 

> Re 'Upload data and use open spending' - we have data from 76 countries (according to openspending.org), which is quite a lot. On the other hand, if I were to judge what openspending does by the current mock, the only 'feature' OpenSpending has is uploading data...

Isn't the first thing you see a search bar that says: search datasets?
From my own experience, I was quite disappointed that when searching for NL in the old open spending, I got a random collection of municipal data from a couple of years ago and not even a link to openspending.nl where all the dutch municipal budget and spending data lives. 
So that is why I would propose to show after the search: this is what we have, please upload more and, these are your countries projects where you may probably find a better answer. In contrast to only showing OS-datasets and 'promise' that you will find your countries financial data (which I read in my first experience with OS as the national budgets, which is not the case).

**Comment by akariv** [comment]
1. Same issue - "search datasets" so I can do what? Why would I search anything if I don't have a clue of what I can do with my findings (e.g. visualise / use for API / whatever)
2. IMO this is a very interesting point (which probably deserves a separate thread) - should we actively seek out and upload budget datasets from around the world to OpenSpending? Adding to that, should we mirror data from other budget/spending portals so that we have the most comprehensive data possible?
I think we should either do that, or go the ckan way (which provide just the platform without hosting any datasets themselves) - any middle way gives a quite disappointing experience (as was yours)
I would say that this is in our best interest, but I accept that there are other arguments against it. 
3. Link to openspending.nl - I agree and it should probably be present as part of the metadata of the FDP. I'll open an issue for that.

**Comment by seegerseeger** [comment]
Hi all, 

I am a colleague of Anna working at Open Budgets. With the alpha version already launched I am a bit late to the discussion, but I still wanted to share a mockup I made after reading this thread. It is more of a structural than a design one, and I also realize the alpha version has changed significantly from Cecile's mock. Perhaps this could still serve as some inspiration for future versions of the site.

My main focus was to give the community and especially its output (projects, stories, applications) more prominence. Especially for newcomers to Open Spending, this could be a way to stimulate involvement. By adding a knowledge base, some of the content that is currently hidden away is re-arranged and more visible. 

At the end of the day, I guess it is a decision on a more general level in terms of Open Spending's identity, which as @akariv mentioned should probably be discussed separately.

![openspending](https://cloud.githubusercontent.com/assets/9677965/16086839/33d2cd7c-3321-11e6-97c5-a36ad0117363.png)

**Comment by cecilaki** [comment]
Hi @seegerseeger and thanks for your mockup and contribution! 
We are definitely more leaning towards this sort of community and knowledge base integration for the future OpenSpending.org landing page. Currently what was released was just an announcement of the new tools and data model that we were working on the past months. 

We definitely want to stimulate engagement from the community and present existing projects and resources that belong to the OpenSpending Ecosystem! 

Thanks for sharing your thoughts in a very visual way, it's very appreciated and helpful!

**Comment by smth** [comment]
I think @seegerseeger 's wireframe is doing a pretty good job of making sense of all this. Have there been any further thoughts on this page?

My 2¢:

It sounds like there is still some discussion to be had about what OpenSpending is. I think due to the amount of stuff it encompasses, we have to think of it as a collection of things. Or the house that the community and the tools etc live in. So, we have to stop thinking of OpenSpending as a tool in itself. With this in mind, for example, saying "search OpenSpending" would mean searching everything.. the data, the community, the tools (which doesn't really make sense).

The user stories will dictate what lives in the OpenSpending house, and this will change over time. One of these things may or may not be a collection of datasets. What we need to do here is:

- Establish what we write on the front door (this metaphor does't work, but I'm sticking with it), i.e What is the common thread? What unites everything in OpenSpending?
- Provide a floorpan to let people get to the room with the stuff they want.

I think the above wireframe does this quite well, but as alluded to, the identity is still up in the air. I like the "tax revenue in Europe.." line as it starts to give some context. Reading it in isolation though, you could be forgiven for thinking that OpenSpending is all about "tax revenue in Europe". This can be addressed in a few ways, but we should make sure that we are clear about what OpenSpending is, in terms of an identity (as opposed to a tool).

Is "how governments spend money" (still) a good description of what OpenSpending is interested in?

**Comment by smth** [comment]
Below is based on the previous wireframe, but limited to content that I could find (so probably stuff missing).

![os_01_home_03](https://cloud.githubusercontent.com/assets/1375708/19104632/a5337c3a-8ad5-11e6-9381-5da8323d2912.jpg)

**Comment by annafralberts** [comment]
I think again it has too much emphasis on the tools, eg. the big panels of viewers, and packager etc. The tools are one block and should include explorer, packager, viewer (not have them all presented on the front page). 
I would say it should emphasise projects and resources more, so that the WHY of OpenSpending comes out clearly on the front page.

**Comment by pwalsh** [comment]
@smth is working on a landing page to use soon. closing this issue.
